# 動作デバイス ( リスト: avr-as -mlist-devices )
DEVICE := attiny10

# 動作クロック(Hz)
CLOCK := 8000000

# プログラマ ( リスト: avrdude -c ? )
PROGRAMMER := -c avrisp2

# ヒューズ
# FUSES = -U BYTE0:w:0xff:m
FUSES = -U BYTE0:w:0xFF:m

# 使用オリジナルライブラリ
MLIBS =

include ../build.mk

